name: Push Generated Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Contents
      uses: actions/checkout@v3

    - name: Pull latest changes from main (to prevent conflicts)
      run: git pull origin main --rebase

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Python Packages Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements

    - name: Execute Python Script
      run: |
        python main.py

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit Files
      run: |
        git add .
        git commit -m "Auto-update config files [skip ci]" || echo "No changes to commit"

    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        branch: main
