name: Execute On Schedule

on:
  schedule:
    - cron: '0 0 * * *'  # Execute every 24h
  workflow_dispatch:        # Optional manual trigger

permissions:
  contents: write  # Required for pushing with a personal token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Contents
        uses: actions/checkout@v4

      - name: Pull Latest Changes
        run: git pull origin main --rebase

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python Packages Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements  # ✅ بدون .txt چون تو واقعاً فایل بدون پسونده
          
      - name: Execute Python Script
        run: python main.py
          
      - name: Configure Git
        run: |
          git config --local user.email "seyyedsoroushmirzaei@protonmail.com"
          git config --local user.name "Soroush Mirzaei"

      - name: Commit Files
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
